name: 'dispatcher'
services:
  webapp:
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - postgres
    environment:
      MODE: ${MODE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${SECRET_ISSUER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      PROFILE_SERVICE_URL: ${PROFILE_SERVICE_URL}
      SQS_URL: ${SQS_URL}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
    ports:
      - ${APP_PORT}

  postgres:
    image: 'postgres:17'
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432"
